apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres-db
          image: postgres:16.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: employee-database
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          resources:
            limits:
              cpu: 500m    # Maximum CPU usage allowed by the container
              memory: 512Mi  # Maximum memory usage allowed by the container
            requests:
              cpu: 100m    # Initial CPU request for the container
              memory: 256Mi  # Initial memory request for the container
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  clusterIP: None
